#!/usr/bin/env bash
# =====================================================================
# run_scalability_test.sh    Sprint 5 Goal 4
#
# Rebuilds the database from 01 + 02 + 04, then loads three sports from
# OUTSIDE the esports domain -- a basketball league, a tennis event with a
# singles and a doubles draw, and a 72-hole golf field -- and replays every
# verification query in 15_scalability_test.sql.
#
#   bash run_scalability_test.sh <root-password>            unfixed schema
#   bash run_scalability_test.sh <root-password> --fixed    with 10_acid_fixes.sql
#
# The two modes write to different files so the pair survives:
#   scalability_test_output.txt        baseline schema
#   scalability_test_output_fixed.txt  after the Sprint 4 fixes
#
# Both modes matter. Several of the findings are about constraints that only
# EXIST after 10_acid_fixes.sql -- the doubles-partner rule (C5), seed
# uniqueness (C4) and the placement-tie rule (C3) are all correct for esports
# and all refuse a legitimate tennis or golf row. Running only the baseline
# would hide them; running only --fixed would hide that they are the fixes'
# doing and not the original schema's.
#
# NOTHING in 01_create_tables.sql, 02_insert_data.sql, 03_test_queries.sql or
# 04_views.sql is edited, patched or reloaded in a modified form. That is the
# entire measurement: S0 fingerprints the schema before the new sports go in,
# S26 fingerprints it afterwards, and the two must be identical.
#
# --force is deliberate. ERROR 1048 (NOT NULL), 1062 (UNIQUE), 1265 (invalid
# ENUM), 1406 (data too long) and 1644 (our own SIGNAL) are all EXPECTED
# RESULTS here -- each one is a test asking the server to refuse a row that a
# real organizer would submit -- so the run must continue past them. -v echoes
# each statement so the transcript pairs every statement with its outcome.
# =====================================================================
set -u

ROOT_PW="${1:?usage: bash run_scalability_test.sh <root-password> [--fixed]}"
MODE="${2:-}"
DB=design_project_370

if [ "$MODE" = "--fixed" ]; then
    OUT=scalability_test_output_fixed.txt
else
    OUT=scalability_test_output.txt
fi
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$(dirname "$0")"

mysql_root() { mysql -u root -p"$ROOT_PW" "$@"; }

echo "==> rebuilding schema, data and views"
mysql_root -e "CREATE DATABASE IF NOT EXISTS $DB;" 2>/dev/null
for f in 01_create_tables.sql 02_insert_data.sql 04_views.sql; do
    if ! mysql_root "$DB" < "$f" 2>"$WORK/err"; then
        echo "FAILED on $f:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  $f"
done

if [ "$MODE" = "--fixed" ]; then
    echo "==> applying 10_acid_fixes.sql"
    if ! mysql_root "$DB" < 10_acid_fixes.sql > "$WORK/10.out" 2>"$WORK/err"; then
        echo "FAILED on 10_acid_fixes.sql:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  10_acid_fixes.sql"
fi

{
    echo "====================================================================="
    echo " SCALABILITY AND FLEXIBILITY TEST TRANSCRIPT"
    echo " Generated by run_scalability_test.sh against MySQL $(mysql_root -N -B -e 'SELECT VERSION();' 2>/dev/null)"
    if [ "$MODE" = "--fixed" ]; then
        echo " Mode: --fixed   (10_acid_fixes.sql applied: 19 triggers, 2 UNIQUE, 6 NOT NULL)"
    else
        echo " Mode: baseline  (01_create_tables.sql exactly as written; no triggers)"
    fi
    echo
    echo " Three sports from outside the esports domain are loaded into the"
    echo " UNMODIFIED schema: a 4-club basketball league, a tennis event with a"
    echo " singles AND a doubles draw, and a 16-player 72-hole golf field."
    echo " Nothing is dropped, altered or weakened first. An INSERT is an INPUT,"
    echo " not a schema change."
    echo
    echo " ERROR 1048 / 1062 / 1265 / 1406 / 1644 lines below are EXPECTED"
    echo " RESULTS, not failures. Each is the server refusing a row a real"
    echo " basketball, tennis or golf organizer would have submitted -- and the"
    echo " refusal IS the finding."
    echo
    echo " Verdicts are computed by COUNT(*) / SUM() against real table"
    echo " contents, never asserted by a literal. Scroll to the SCORECARD at"
    echo " the bottom."
    echo "====================================================================="
    echo
} > "$OUT"

echo "==> replaying 15_scalability_test.sql"
mysql_root --force -t -v --comments "$DB" < 15_scalability_test.sql >> "$OUT" 2>&1

{
    echo
    echo "====================================================================="
    echo " SUMMARY"
    echo "====================================================================="
} >> "$OUT"

mysql_root -t "$DB" -e "
    SELECT verdict, COUNT(*) AS n FROM scalability_results
     GROUP BY verdict ORDER BY verdict;
    SELECT test, scenario, verdict, evidence FROM scalability_results
     WHERE verdict <> 'PASS' ORDER BY seq;
    SELECT test, scenario, compromise FROM scalability_results
     WHERE compromise IS NOT NULL ORDER BY seq;
" >> "$OUT" 2>&1

echo "==> wrote $OUT"

# Read the counts back out of the database rather than grepping the transcript:
# the words PASS and GAP appear inside the SQL text itself, so grep would lie.
PASSES=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM scalability_results WHERE verdict = 'PASS';" 2>/dev/null)
GAPS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM scalability_results WHERE verdict = 'GAP';" 2>/dev/null)
FAILS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM scalability_results WHERE verdict = 'FAIL';" 2>/dev/null)

echo "    PASS : ${PASSES:-?}   (loaded and read back correctly, zero schema change)"
echo "    GAP  : ${GAPS:-?}   (accepted but meaningless, or refused a legitimate row)"
echo "    FAIL : ${FAILS:-?}   (a precondition of the test itself did not hold -- investigate)"
echo

# The headline number: the schema fingerprint before vs after.
mysql_root -t "$DB" -e \
    "SELECT test, verdict, evidence FROM scalability_results WHERE test IN ('S0','S26');" \
    2>/dev/null

echo
mysql_root -t "$DB" -e \
    "SELECT scenario
          , SUM(verdict = 'PASS') AS pass
          , SUM(verdict = 'GAP')  AS gap
          , SUM(verdict = 'FAIL') AS fail
          , SUM(compromise IS NOT NULL) AS compromised
       FROM scalability_results
      GROUP BY scenario
      ORDER BY FIELD(scenario,'BASELINE','BASKETBALL','TENNIS','GOLF','CROSS');" \
    2>/dev/null

echo
echo "==> also run the other mode for the full picture:"
if [ "$MODE" = "--fixed" ]; then
    echo "    bash run_scalability_test.sh <root-password>"
else
    echo "    bash run_scalability_test.sh <root-password> --fixed"
fi
