#!/usr/bin/env bash
# =====================================================================
# run_acid_tests.sh
#
# Rebuilds the database from scratch, installs the corrected transaction
# workload (07), then replays the single-session ACID evidence (08) and
# captures the whole transcript to acid_test_output.txt.
#
#   bash run_acid_tests.sh <root-password>            baseline, unfixed schema
#   bash run_acid_tests.sh <root-password> --fixed    with 10_acid_fixes.sql applied
#
# The two modes write to different files so the before/after pair survives:
#   acid_test_output.txt        baseline
#   acid_test_output_fixed.txt  after the fixes
#
# --force is deliberate. ERROR 3819 (CHECK), 1451/1452 (foreign key) and
# 1644 (our own SIGNAL) are all EXPECTED RESULTS here, not failures, so the
# run must continue past them. -v echoes each statement so the transcript
# pairs every statement with its outcome.
#
# NOT run by this script:
#   09_isolation_tests_a.sql / _b.sql -- need two connections interleaving.
#       Run them by hand in two terminals; see the header of _a.sql.
#   durability -- needs the server killed mid-run. See the README.
# =====================================================================
set -u

ROOT_PW="${1:?usage: bash run_acid_tests.sh <root-password> [--fixed]}"
MODE="${2:-}"
DB=design_project_370

if [ "$MODE" = "--fixed" ]; then
    OUT=acid_test_output_fixed.txt
else
    OUT=acid_test_output.txt
fi
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$(dirname "$0")"

mysql_root() { mysql -u root -p"$ROOT_PW" "$@"; }

echo "==> rebuilding schema, data, views and grants"
mysql_root -e "CREATE DATABASE IF NOT EXISTS $DB;" 2>/dev/null
for f in 01_create_tables.sql 02_insert_data.sql 04_views.sql 05_roles_and_grants.sql; do
    if ! mysql_root "$DB" < "$f" 2>"$WORK/err"; then
        echo "FAILED on $f:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  $f"
done

# 07 must apply cleanly. Unlike 08, an error here is a real failure: the
# procedures are the fixed workload, not a test.
echo "==> installing the transaction workload"
if ! mysql_root "$DB" < 07_transactions.sql > "$WORK/07.out" 2>"$WORK/err"; then
    echo "FAILED on 07_transactions.sql:"; cat "$WORK/err"; exit 1
fi
echo "    ok  07_transactions.sql"

if [ "$MODE" = "--fixed" ]; then
    echo "==> applying 10_acid_fixes.sql"
    if ! mysql_root "$DB" < 10_acid_fixes.sql > "$WORK/10.out" 2>"$WORK/err"; then
        echo "FAILED on 10_acid_fixes.sql:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  10_acid_fixes.sql"
fi

{
    echo "====================================================================="
    echo " ACID TEST TRANSCRIPT"
    echo " Generated by run_acid_tests.sh against MySQL $(mysql_root -N -B -e 'SELECT VERSION();' 2>/dev/null)"
    echo
    echo " Every statement below runs against the UNMODIFIED schema from"
    echo " 01_create_tables.sql. Nothing is dropped, altered or weakened first."
    echo
    echo " ERROR 3819 (CHECK), 1451/1452 (foreign key) and 1644 (our own SIGNAL)"
    echo " are EXPECTED RESULTS, not failures. In the -FIX tests an ERROR 1644 is"
    echo " a PASS: a procedure from 07_transactions.sql refusing the statement."
    echo
    echo " Verdicts are computed by COUNT(*) against real table contents, never"
    echo " asserted by a literal. Scroll to the VERDICT TABLE at the bottom."
    echo "====================================================================="
    echo
    cat "$WORK/07.out"
} > "$OUT"

echo "==> replaying 08_acid_tests.sql"
mysql_root --force -t -v --comments "$DB" < 08_acid_tests.sql >> "$OUT" 2>&1

{
    echo
    echo "====================================================================="
    echo " SUMMARY"
    echo "====================================================================="
} >> "$OUT"

mysql_root -t "$DB" -e "
    SELECT verdict, COUNT(*) AS n FROM acid_results GROUP BY verdict ORDER BY verdict;
    SELECT test, property, verdict, evidence FROM acid_results
     WHERE verdict <> 'OK' ORDER BY seq;
" >> "$OUT" 2>&1

echo "==> wrote $OUT"

# Read the counts back out of the database rather than grepping the transcript:
# the words GAP and OK appear inside the SQL text itself, so grep would lie.
GAPS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM acid_results WHERE verdict = 'GAP';" 2>/dev/null)
FAILS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM acid_results WHERE verdict = 'FAIL';" 2>/dev/null)
OKS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM acid_results WHERE verdict = 'OK';" 2>/dev/null)

echo "    OK   : ${OKS:-?}   (the DBMS or a procedure refused the bad statement)"
echo "    GAP  : ${GAPS:-?}   (accepted something it should have refused)"
echo "    FAIL : ${FAILS:-?}   (a fix or a precondition did not hold -- investigate)"
echo
mysql_root -t "$DB" -e \
    "SELECT test, verdict, evidence FROM acid_results WHERE verdict <> 'OK' ORDER BY seq;" \
    2>/dev/null

echo
echo "==> still to run by hand:"
echo "    isolation  two terminals, 09_isolation_tests_a.sql + 09_isolation_tests_b.sql"
echo "    durability see the Sprint 4 section of ../README.md"
