#!/usr/bin/env bash
# =====================================================================
# run_null_tests.sh
#
# Rebuilds the database from scratch, installs the Sprint 3 views, then replays
# the null-safety evidence (11) and captures the whole transcript to
# null_test_output.txt.
#
#   bash run_null_tests.sh <root-password>            baseline, views as shipped
#   bash run_null_tests.sh <root-password> --fixed    with 12_null_fixes.sql applied
#
# The two modes write to different files so the before/after pair survives:
#   null_test_output.txt        baseline
#   null_test_output_fixed.txt  after the fixes
#
# This is the MEASURE for Sprint 5 goal 1. Run both, then compare the MEASURE
# row at the bottom of each transcript:
#   baseline  ->  N of 16 views lose rows or values to NULL
#   --fixed   ->  0 of 16
#
# The same 11_null_tests.sql runs in both modes. Nothing in it is told which
# mode it is in -- it reads the view definitions out of information_schema
# (P0-mode) and compares each shipped view against an inline null-safe rewrite
# of itself. That is what makes the second number a measurement rather than a
# claim.
#
# --force is deliberate, for the same reason as in run_acid_tests.sh: the run
# must not stop on a statement whose failure is itself a result. -v echoes each
# statement so the transcript pairs every statement with its outcome.
#
# 05_roles_and_grants.sql is NOT applied. Every test here runs as root; the
# row-level-security views are exercised by moving db_username onto 'root'
# inside a transaction that is then rolled back. See the header of
# 11_null_tests.sql.
#
# NOT run by this script:
#   06_permission_tests.sql  -- needs one connection per demo account
#   08 / 09 / durability     -- see run_acid_tests.sh and the README
# =====================================================================
set -u

ROOT_PW="${1:?usage: bash run_null_tests.sh <root-password> [--fixed]}"
MODE="${2:-}"
DB=design_project_370

if [ "$MODE" = "--fixed" ]; then
    OUT=null_test_output_fixed.txt
else
    OUT=null_test_output.txt
fi
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$(dirname "$0")"

mysql_root() { mysql -u root -p"$ROOT_PW" "$@"; }

echo "==> rebuilding schema, data and views"
mysql_root -e "CREATE DATABASE IF NOT EXISTS $DB;" 2>/dev/null
for f in 01_create_tables.sql 02_insert_data.sql 04_views.sql; do
    if ! mysql_root "$DB" < "$f" 2>"$WORK/err"; then
        echo "FAILED on $f:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  $f"
done

if [ "$MODE" = "--fixed" ]; then
    # An error here is a real failure: 12 is the fix, not a test. Its Part B
    # emits the corrected Q1/Q7/Q8/Q9/Q11 results, which are prepended to the
    # transcript below.
    echo "==> applying 12_null_fixes.sql"
    if ! mysql_root -t "$DB" < 12_null_fixes.sql > "$WORK/12.out" 2>"$WORK/err"; then
        echo "FAILED on 12_null_fixes.sql:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  12_null_fixes.sql"
else
    : > "$WORK/12.out"
fi

{
    echo "====================================================================="
    echo " NULL SAFETY / DANGLING TUPLE TRANSCRIPT"
    echo " Generated by run_null_tests.sh against MySQL $(mysql_root -N -B -e 'SELECT VERSION();' 2>/dev/null)"
    if [ "$MODE" = "--fixed" ]; then
        echo " Mode: FIXED -- 12_null_fixes.sql applied on top of 04_views.sql"
    else
        echo " Mode: BASELINE -- views exactly as 04_views.sql shipped them"
    fi
    echo
    echo " Every test runs the SHIPPED view or query and an inline null-safe"
    echo " rewrite of itself side by side. The difference between the two row"
    echo " counts IS the number of dangling tuples; no verdict is asserted by a"
    echo " literal. Every test rolls back, and RESIDUE at the bottom proves it."
    echo
    echo " GAP  = rows or values a user should see are being discarded."
    echo " OK   = null-safe, or the inner join is the intended semantics."
    echo " FAIL = a control or a precondition did not hold -- investigate."
    echo
    echo " Read the MEASURE row at the bottom first: it is the Sprint 5 number."
    echo "====================================================================="
    echo
    if [ -s "$WORK/12.out" ]; then
        echo "--------------------------------------------------------------------"
        echo " 12_null_fixes.sql PART B -- the corrected Q1 / Q7 / Q8 / Q9 / Q11"
        echo "--------------------------------------------------------------------"
        cat "$WORK/12.out"
        echo
    fi
} > "$OUT"

echo "==> replaying 11_null_tests.sql"
mysql_root --force -t -v --comments "$DB" < 11_null_tests.sql >> "$OUT" 2>&1

{
    echo
    echo "====================================================================="
    echo " SUMMARY"
    echo "====================================================================="
} >> "$OUT"

mysql_root -t "$DB" -e "
    SELECT verdict, COUNT(*) AS n FROM null_results GROUP BY verdict ORDER BY verdict;
    SELECT kind
         , SUM(verdict = 'GAP')  AS gaps
         , SUM(verdict = 'OK')   AS oks
         , SUM(verdict = 'FAIL') AS fails
      FROM null_results GROUP BY kind ORDER BY kind;
    SELECT test, kind, target, verdict, evidence FROM null_results
     WHERE verdict <> 'OK' ORDER BY seq;
" >> "$OUT" 2>&1

echo "==> wrote $OUT"

# Read the counts back out of the database rather than grepping the transcript:
# the words GAP and OK appear inside the SQL text itself, so grep would lie.
GAPS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM null_results WHERE verdict = 'GAP' AND kind <> 'summary';" 2>/dev/null)
FAILS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM null_results WHERE verdict = 'FAIL';" 2>/dev/null)
OKS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM null_results WHERE verdict = 'OK';" 2>/dev/null)
VIEWGAPS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(DISTINCT target) FROM null_results WHERE kind = 'view' AND verdict = 'GAP';" 2>/dev/null)
NVIEWS=$(mysql_root -N -B "$DB" -e \
    "SELECT COUNT(*) FROM information_schema.VIEWS WHERE TABLE_SCHEMA = '$DB';" 2>/dev/null)

echo "    OK   : ${OKS:-?}   (null-safe, or the inner join is the intended semantics)"
echo "    GAP  : ${GAPS:-?}   (rows or values a user should see are discarded)"
echo "    FAIL : ${FAILS:-?}   (a control or a precondition did not hold -- investigate)"
echo
echo "    MEASURE: ${VIEWGAPS:-?} of ${NVIEWS:-?} views drop rows or values to NULL"
echo

mysql_root -t "$DB" -e \
    "SELECT test, target, verdict, evidence FROM null_results
      WHERE verdict <> 'OK' ORDER BY seq;" \
    2>/dev/null

echo
if [ "$MODE" = "--fixed" ]; then
    echo "==> baseline for comparison:  bash run_null_tests.sh <root-password>"
else
    echo "==> now run the fixed pass:   bash run_null_tests.sh <root-password> --fixed"
fi
