#!/usr/bin/env bash
# =====================================================================
# run_ui_setup.sh
#
# Builds the UI-ready database from scratch: schema, seed data, views,
# roles, the ACID and null fixes, then the two post-semester UI layers
# (17_ui_readiness.sql + 18_ui_seed_fill.sql). Finishes with smoke
# queries that prove every UI-blocking gap is closed, captured to
# ui_setup_output.txt.
#
#   bash run_ui_setup.sh <root-password>
#   bash run_ui_setup.sh                # reads MYSQL_PASSWORD from ../.env
#
# NOTE: this build deliberately excludes 13_bulk_data.sql. The bulk
# layer exists to stress indexes and its ids overlap 18's; a UI demo
# database and a bulk stress database are rebuilt separately.
# =====================================================================
set -u

cd "$(dirname "$0")"

ROOT_PW="${1:-}"
if [ -z "$ROOT_PW" ] && [ -f ../.env ]; then
    ROOT_PW="$(sed -n 's/^MYSQL_PASSWORD=//p' ../.env | tr -d '\r')"
fi
if [ -z "$ROOT_PW" ] || [ "$ROOT_PW" = "PUT_YOUR_PASSWORD_HERE" ]; then
    echo "usage: bash run_ui_setup.sh <root-password>   (or set MYSQL_PASSWORD in ../.env)"
    exit 1
fi
DEMO_PW='Csc370demo!'
DB=design_project_370
OUT=ui_setup_output.txt

mysqlr() { mysql -u root -p"$ROOT_PW" "$@"; }

echo "==> rebuilding $DB from scratch"
mysqlr -e "DROP DATABASE IF EXISTS $DB; CREATE DATABASE $DB;" || exit 1

for f in 01_create_tables.sql 02_insert_data.sql 04_views.sql \
         05_roles_and_grants.sql 10_acid_fixes.sql 12_null_fixes.sql \
         17_ui_readiness.sql 18_ui_seed_fill.sql; do
    if ! mysqlr "$DB" < "$f" > /dev/null 2>/tmp/ui_setup_err; then
        echo "FAILED on $f:"; cat /tmp/ui_setup_err; exit 1
    fi
    echo "    ok  $f"
done

# 05 predates the bracket view; grant it alongside the other public views.
mysqlr "$DB" -e "GRANT SELECT ON $DB.v_public_bracket TO 'role_audience';" \
    && echo "    ok  grant v_public_bracket -> role_audience"

{
    echo "====================================================================="
    echo " UI SETUP SMOKE TESTS"
    echo " Generated by run_ui_setup.sh against MySQL $(mysqlr -N -B -e 'SELECT VERSION();' 2>/dev/null)"
    echo "====================================================================="

    echo
    echo "--- 1. tournament states: the UI can now show live and upcoming events"
    mysqlr -t "$DB" -e "SELECT tournament_id, name, status, score_direction FROM Tournament ORDER BY tournament_id;"

    echo
    echo "--- 2. bracket view: rounds and slots, TBD final, winners per match"
    mysqlr -t "$DB" -e "SELECT * FROM v_public_bracket WHERE tournament_id IN (1,5,6) ORDER BY tournament_id, round, bracket_slot;"

    echo
    echo "--- 3. solo payouts: payee_type now covers players (expect 3 kinds)"
    mysqlr -t "$DB" -e "SELECT payee_type, COUNT(*) AS payments, SUM(amount) AS total FROM Payments GROUP BY payee_type;"

    echo
    echo "--- 4. outstanding payments as admin_mtb: player + staff + team debts"
    mysql -u admin_mtb -p"$DEMO_PW" -t "$DB" -e "SELECT * FROM v_outstanding_payments ORDER BY amount DESC;" 2>&1

    echo
    echo "--- 5. creators now have display names on the deliverable tracker"
    mysqlr -t "$DB" -e "SELECT DISTINCT party, party_type FROM v_deliverable_status;"

    echo
    echo "--- 6. captain -> team navigation"
    mysqlr -t "$DB" -e "SELECT tm.team_name, u.full_name AS captain FROM Teams tm JOIN Users u ON u.user_id = tm.captain_user_id;"

    echo
    echo "--- 7. player profiles filled (country/birth_date; real_name only for"
    echo "---    the fictional solo entrants, by design)"
    mysqlr -t "$DB" -e "SELECT COUNT(*) AS players, SUM(country IS NOT NULL) AS with_country, SUM(real_name IS NOT NULL) AS with_real_name FROM Players;"

    echo
    echo "--- 8. EXPECTED FAILURE: prize pools are exactly consumed, so one more"
    echo "---    player payout must be rejected by the extended trigger"
    mysqlr --force -t "$DB" -e "INSERT INTO Payments (payee_type, staff_user_id, team_id, player_id, tournament_id, amount, status, payment_date) VALUES ('player', NULL, NULL, 47, 3, 1.00, 'paid', '2026-05-06');" 2>&1

    echo
    echo "--- 9. standings still rank every format (team bracket, TFT lobby, 1v1)"
    mysqlr -t "$DB" -e "SELECT tournament, standing, competitor, competitor_type, total_points FROM v_public_standings WHERE tournament_id IN (3,4,5) ORDER BY tournament_id, standing;"
} > "$OUT" 2>&1

echo "==> wrote $OUT"
grep -c 'ERROR' "$OUT" | xargs echo "    error lines in transcript (expect exactly 1, the trigger rejection):"
