#!/usr/bin/env bash
# =====================================================================
# run_permission_tests.sh
#
# Rebuilds the database, applies views and grants, then replays
# 06_permission_tests.sql once per demo account -- each block as the user named
# in its own header comment -- and captures the transcript, denials included,
# to permission_test_output.txt.
#
#   bash run_permission_tests.sh <root-password>
#
# --force is deliberate: an ERROR 1142 is an EXPECTED result here, not a
# failure, so the run must continue past it. -v echoes each statement so the
# transcript pairs every statement with its outcome.
# =====================================================================
set -u

ROOT_PW="${1:?usage: bash run_permission_tests.sh <root-password>}"
DEMO_PW='Csc370demo!'
DB=design_project_370
OUT=permission_test_output.txt
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$(dirname "$0")"

echo "==> rebuilding schema, data, views and grants"
mysql -u root -p"$ROOT_PW" -e "CREATE DATABASE IF NOT EXISTS $DB;" 2>/dev/null
for f in 01_create_tables.sql 02_insert_data.sql 04_views.sql 05_roles_and_grants.sql; do
    if ! mysql -u root -p"$ROOT_PW" "$DB" < "$f" 2>"$WORK/err"; then
        echo "FAILED on $f:"; cat "$WORK/err"; exit 1
    fi
    echo "    ok  $f"
done

# Split 06 into one chunk per TEST block; each chunk's header names its account.
# Zero-padded so the shell glob below orders TEST 10 after TEST 9, not after TEST 1.
awk '/^-- TEST [0-9]+ /{n++} n>0{printf "%s\n", $0 > (sprintf("'"$WORK"'/chunk%02d.sql", n))}' 06_permission_tests.sql

{
    echo "====================================================================="
    echo " PERMISSION TEST TRANSCRIPT"
    echo " Generated by run_permission_tests.sh against MySQL $(mysql -u root -p"$ROOT_PW" -N -B -e 'SELECT VERSION();' 2>/dev/null)"
    echo
    echo " ERROR 1142 / 1143 lines below are EXPECTED RESULTS, not failures."
    echo " A query that succeeds proves a grant is wide enough; only a denial"
    echo " proves it is tight enough."
    echo "====================================================================="
} > "$OUT"

for chunk in "$WORK"/chunk*.sql; do
    [ -e "$chunk" ] || continue
    user=$(sed -n 's/^-- mysql -u \([A-Za-z_0-9]*\).*/\1/p' "$chunk" | head -1)
    label=$(sed -n 's/^-- TEST \(.*\)/\1/p' "$chunk" | head -1)
    [ -n "$user" ] || continue

    if [ "$user" = root ]; then pw="$ROOT_PW"; else pw="$DEMO_PW"; fi

    {
        echo
        echo "#####################################################################"
        echo "# TEST $label     (connected as: $user)"
        echo "#####################################################################"
    } >> "$OUT"

    mysql -u "$user" -p"$pw" --force -t -v --comments "$DB" < "$chunk" >> "$OUT" 2>&1
    echo "    ran TEST $label as $user"
done

echo "==> wrote $OUT"
grep -c 'ERROR 114' "$OUT" | xargs echo "    denials captured:"
